"""
Backtesting Engine for PDAI Trading Bot
Simulates trading strategies on historical data
"""
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from decimal import Decimal
import logging
from typing import Dict, List, Optional, Tuple
import json
import os

from bot.config import Config
from strategies.base_strategy import BaseStrategy

logger = logging.getLogger(__name__)

class BacktestEngine:
    """Backtesting engine for trading strategies"""
    
    def __init__(self, initial_balance: float = None):
        self.config = Config()
        self.initial_balance = Decimal(str(initial_balance or self.config.INITIAL_BALANCE))
        self.reset()
        
    def reset(self):
        """Reset backtest state"""
        self.balance = self.initial_balance
        self.pdai_balance = Decimal('0')
        self.trades = []
        self.portfolio_history = []
        self.position = None  # 'long', 'short', or None
        self.entry_price = None
        self.entry_time = None
        self.total_fees = Decimal('0')
        self.max_drawdown = Decimal('0')
        self.peak_balance = self.initial_balance
        
    def run_backtest(self, strategy: BaseStrategy, data: pd.DataFrame,
                    trade_amount_pct: Optional[float] = None, slippage_pct: float = 0.01) -> Dict:
        """
        Run backtest on historical data
        
        Args:
            strategy: Trading strategy to test
            data: Historical price data
            trade_amount_pct: Percentage of balance to use per trade (0.0-1.0)
            slippage_pct: Slippage percentage to apply to trades (0.01 = 1%)
            
        Returns:
            Dictionary with backtest results
        """
        if data.empty:
            return {'error': 'No data provided for backtesting'}
        
        logger.info(f"Starting backtest for {strategy.name} on {len(data)} data points")
        
        self.reset()
        
        # Calculate indicators and signals for all data at once
        data_with_indicators = strategy.calculate_indicators(data.copy())
        signals_data = strategy.generate_signals(data_with_indicators)
        
        if signals_data.empty:
            return {'error': 'No signals generated by strategy'}
        
        if trade_amount_pct is None:
            params = getattr(strategy, 'parameters', {}) or {}
            trade_amount_pct = params.get('trade_amount_pct', getattr(strategy, 'trade_amount_pct', 1.0))
        try:
            trade_amount_pct = float(trade_amount_pct)
        except (TypeError, ValueError):
            trade_amount_pct = 1.0
        trade_amount_pct = min(1.0, max(0.0, trade_amount_pct))  # Clamp to 0-100%
        slippage_pct = min(0.1, max(0.0, slippage_pct))  # Clamp between 0% and 10%
        
        # Simulate trading through the data
        for i in range(len(signals_data)):
            current_data = signals_data.iloc[i]
            
            # Process the current signal
            self._process_signal(
                current_data,
                trade_amount_pct,
                slippage_pct,
                i
            )
            
            # Record portfolio state
            self._record_portfolio_state(current_data)
        
        # Close any open position at the end
        if self.position:
            price_col = 'price' if 'price' in signals_data.columns else 'close'
            final_price = Decimal(str(float(signals_data.iloc[-1][price_col])))  # Convert to Decimal
            final_time = signals_data.iloc[-1]['timestamp']
            self._close_position(final_price, final_time, 'backtest_end')
        
        # Calculate results
        results = self._calculate_results(signals_data)
        
        logger.info(f"Backtest completed: {len(self.trades)} trades, "
                   f"Final balance: {self.balance:.4f} DAI")
        
        return results
    
    def _process_signal(self, current_data: pd.Series, trade_amount_pct: float, slippage_pct: float, index: int):
        """Process a single trading signal with slippage"""
        # Use 'close' column as price if 'price' doesn't exist
        price_col = 'price' if 'price' in current_data else 'close'
        base_price = Decimal(str(float(current_data[price_col])))  # Ensure float conversion first
        # Convert timestamp to datetime if it's a string
        timestamp = current_data['timestamp']
        if isinstance(timestamp, str):
            timestamp = pd.to_datetime(timestamp)
        
        buy_signal = current_data.get('buy_signal', False)
        sell_signal = current_data.get('sell_signal', False)
        signal_strength = current_data.get('signal_strength', 0.0)
        
        # Skip if no signal (signal_strength of 0 means no signal)
        # Let strategies control their own minimum thresholds
        if signal_strength <= 0:
            return
        
        # Buy signal - enter long position
        if buy_signal and self.position != 'long':
            if self.position == 'short':
                # Close short position first (not implemented in this simple version)
                pass
            
            # Enter long position (buy PDAI with DAI via routing through WPLS)
            trade_amount = self.balance * Decimal(str(trade_amount_pct))
            
            if trade_amount > Decimal('0.01'):  # Minimum trade amount
                # Apply slippage - we pay more when buying
                slippage_multiplier = Decimal('1') + Decimal(str(slippage_pct))
                price = base_price * slippage_multiplier
                
                # Calculate fees (simulate PulseX fees ~0.25%)
                fee_rate = Decimal('0.0025')
                fee = trade_amount * fee_rate
                net_amount = trade_amount - fee
                
                # Calculate PDAI amount received
                pdai_received = net_amount / price
                
                # Update balances
                self.balance -= trade_amount
                self.pdai_balance += pdai_received
                self.total_fees += fee
                
                # Record trade
                trade = {
                    'timestamp': timestamp,
                    'type': 'buy',
                    'price': float(price),
                    'quote_amount': float(trade_amount),
                    'pdai_amount': float(pdai_received),
                    'fee': float(fee),
                    'signal_strength': signal_strength,
                    'balance_after': float(self.balance),
                    'index': index
                }
                
                self.trades.append(trade)
                
                # Set position
                self.position = 'long'
                self.entry_price = price
                self.entry_time = timestamp
                
                logger.debug(f"BUY: {pdai_received:.4f} PDAI at {price:.8f} DAI")
        
        # Sell signal - exit long position
        elif sell_signal and self.position == 'long':
            # Apply slippage - we receive less when selling
            slippage_multiplier = Decimal('1') - Decimal(str(slippage_pct))
            price = base_price * slippage_multiplier
            self._close_position(price, timestamp, 'sell_signal', signal_strength, index)
    
    def _close_position(self, price: Decimal, timestamp, reason: str, 
                       signal_strength: float = 1.0, index: int = None):
        """Close current position"""
        if self.position != 'long' or self.pdai_balance <= 0:
            return
        
        # Calculate quote (DAI) amount received
        quote_gross = self.pdai_balance * price
        
        # Calculate fees
        fee_rate = Decimal('0.0025')
        fee = quote_gross * fee_rate
        quote_net = quote_gross - fee
        
        # Update balances
        self.balance += quote_net
        pdai_sold = self.pdai_balance
        self.pdai_balance = Decimal('0')
        self.total_fees += fee
        
        # Calculate P&L
        if self.entry_price:
            pnl = (price - self.entry_price) / self.entry_price * Decimal('100')  # Percentage
            pnl_quote = quote_net - (pdai_sold * self.entry_price)
        else:
            pnl = Decimal('0')
            pnl_quote = Decimal('0')
        
        # Record trade
        trade = {
            'timestamp': timestamp,
            'type': 'sell',
            'price': float(price),
            'quote_amount': float(quote_net),
            'pdai_amount': float(pdai_sold),
            'fee': float(fee),
            'signal_strength': signal_strength,
            'balance_after': float(self.balance),
            'pnl_pct': float(pnl),
            'pnl_quote': float(pnl_quote),
            'entry_price': float(self.entry_price) if self.entry_price else 0,
            'entry_time': self.entry_time,
            'hold_duration': str(timestamp - self.entry_time) if self.entry_time else None,
            'reason': reason,
            'index': index or 0
        }
        
        self.trades.append(trade)
        
        # Reset position
        self.position = None
        self.entry_price = None
        self.entry_time = None
        
        logger.debug(f"SELL: {pdai_sold:.4f} PDAI at {price:.8f} DAI, P&L: {pnl:.2f}%")
    
    def _record_portfolio_state(self, current_data: pd.Series):
        """Record current portfolio state for analysis"""
        price_col = 'price' if 'price' in current_data else 'close'
        price = Decimal(str(float(current_data[price_col])))  # Ensure float conversion first
        timestamp = current_data['timestamp']
        
        # Calculate total portfolio value
        pdai_value = self.pdai_balance * price
        total_value = self.balance + pdai_value
        
        # Update peak balance and max drawdown
        if total_value > self.peak_balance:
            self.peak_balance = total_value
        
        drawdown = (self.peak_balance - total_value) / self.peak_balance
        if drawdown > self.max_drawdown:
            self.max_drawdown = drawdown
        
        # Record state
        state = {
            'timestamp': timestamp,
            'price': float(price),
            'quote_balance': float(self.balance),
            'pdai_balance': float(self.pdai_balance),
            'pdai_value_quote': float(pdai_value),
            'total_value': float(total_value),
            'position': self.position,
            'drawdown': float(drawdown)
        }
        
        self.portfolio_history.append(state)
    
    def _calculate_results(self, data: pd.DataFrame) -> Dict:
        """Calculate comprehensive backtest results"""
        if not self.trades:
            return {
                'strategy': 'No trades executed',
                'initial_balance': float(self.initial_balance),
                'final_balance': float(self.balance),
                'total_return': 0.0,
                'error': 'No trades were executed'
            }
        
        # Basic metrics
        price_col = 'price' if 'price' in data.columns else 'close'
        final_balance = self.balance + (self.pdai_balance * Decimal(str(data.iloc[-1][price_col])))
        total_return = (final_balance - self.initial_balance) / self.initial_balance * 100
        
        # Trade analysis
        buy_trades = [t for t in self.trades if t['type'] == 'buy']
        sell_trades = [t for t in self.trades if t['type'] == 'sell']
        
        # P&L analysis from sell trades
        profitable_trades = [t for t in sell_trades if t.get('pnl_pct', 0) > 0]
        losing_trades = [t for t in sell_trades if t.get('pnl_pct', 0) < 0]
        
        win_rate = (len(profitable_trades) / len(sell_trades) * 100) if sell_trades else 0
        
        avg_win = np.mean([t['pnl_pct'] for t in profitable_trades]) if profitable_trades else 0
        avg_loss = np.mean([t['pnl_pct'] for t in losing_trades]) if losing_trades else 0
        
        # Risk metrics
        if self.portfolio_history:
            portfolio_df = pd.DataFrame(self.portfolio_history)
            portfolio_df['returns'] = portfolio_df['total_value'].pct_change()
            
            volatility = portfolio_df['returns'].std() * np.sqrt(252 * 24 * 60) * 100  # Annualized
            
            # Sharpe ratio (simplified, assuming 0% risk-free rate)
            mean_return = portfolio_df['returns'].mean()
            sharpe_ratio = (mean_return / portfolio_df['returns'].std()) if portfolio_df['returns'].std() > 0 else 0
            sharpe_ratio *= np.sqrt(252 * 24 * 60)  # Annualized
        else:
            volatility = 0
            sharpe_ratio = 0
        
        # Time analysis
        start_time = data.iloc[0]['timestamp']
        end_time = data.iloc[-1]['timestamp']
        # Convert to datetime if strings
        if isinstance(start_time, str):
            start_time = pd.to_datetime(start_time)
        if isinstance(end_time, str):
            end_time = pd.to_datetime(end_time)
        duration = end_time - start_time
        
        results = {
            # Basic metrics
            'strategy_name': 'Backtest Results',
            'start_time': start_time.strftime('%Y-%m-%d %H:%M:%S'),
            'end_time': end_time.strftime('%Y-%m-%d %H:%M:%S'),
            'duration_days': duration.days,
            'data_points': len(data),
            
            # Performance
            'initial_balance': float(self.initial_balance),
            'final_balance': float(final_balance),
            'total_return_pct': float(total_return),
            'total_fees': float(self.total_fees),
            
            # Trading metrics
            'total_trades': len(self.trades),
            'buy_trades': len(buy_trades),
            'sell_trades': len(sell_trades),
            'win_rate_pct': float(win_rate),
            'profitable_trades': len(profitable_trades),
            'losing_trades': len(losing_trades),
            
            # P&L metrics
            'avg_win_pct': float(avg_win),
            'avg_loss_pct': float(avg_loss),
            'profit_factor': float(abs(avg_win / avg_loss)) if avg_loss != 0 else 0,
            
            # Risk metrics
            'max_drawdown_pct': float(self.max_drawdown * 100),
            'volatility_pct': float(volatility),
            'sharpe_ratio': float(sharpe_ratio),
            
            # Additional data
            'trades': self.trades,
            'portfolio_history': self.portfolio_history
        }
        
        return results
    
    def save_results(self, results: Dict, filename: str = None):
        """Save backtest results to file"""
        if filename is None:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = os.path.join(self.config.DATA_DIR, f"backtest_results_{timestamp}.json")
        
        try:
            # Make results JSON serializable
            json_results = json.loads(json.dumps(results, default=str))
            
            with open(filename, 'w') as f:
                json.dump(json_results, f, indent=2)
            
            logger.info(f"Results saved to {filename}")
            return filename
            
        except Exception as e:
            logger.error(f"Error saving results: {e}")
            return None
    
    def get_trade_summary(self) -> str:
        """Get a formatted summary of trades"""
        if not self.trades:
            return "No trades executed"
        
        buy_trades = [t for t in self.trades if t['type'] == 'buy']
        sell_trades = [t for t in self.trades if t['type'] == 'sell']
        
        summary = f"Trade Summary:\n"
        summary += f"  Total trades: {len(self.trades)}\n"
        summary += f"  Buy orders: {len(buy_trades)}\n"
        summary += f"  Sell orders: {len(sell_trades)}\n"
        summary += f"  Total fees: {self.total_fees:.6f} DAI\n"
        
        if sell_trades:
            profitable = [t for t in sell_trades if t.get('pnl_pct', 0) > 0]
            win_rate = len(profitable) / len(sell_trades) * 100
            avg_pnl = np.mean([t.get('pnl_pct', 0) for t in sell_trades])
            
            summary += f"  Win rate: {win_rate:.1f}%\n"
            summary += f"  Average P&L: {avg_pnl:.2f}%\n"
        
        return summary
