//
// @author LazyBear
//
// Volume ROC is calculated by dividing the amount the volume changed over the last
// "n" days by volume "n" days ago. The result is the % volume change. 
//
// If volume today is higher than "n" days ago, VROC will be positive, else negative. 
//
study(title = "Volume ROC [LazyBear]", shorttitle="VolumeROC[LB]")
length=input(12)
vroc = ((volume - volume[length]) / (volume[length])) * 100
hline(0, color=gray)
plot(vroc)