//
// @author LazyBear
// If you use this code, in its original or modified form, do drop me a note. Thx. 
//
study("HawkEye Volume Indicator [LazyBear]", shorttitle="HVI_LB")
length=input(200)
range=high-low
rangeAvg=sma(range,length)

volumeA=sma(volume, length)
divisor=input(3.6)

high1=high[1]
low1=low[1]
mid1=hl2[1]

u1 = mid1 + (high1-low1)/divisor
d1 = mid1 - (high1-low1)/divisor

r_enabled1 = (range > rangeAvg) and (close < d1) and volume > volumeA
r_enabled2 = close < mid1
r_enabled = r_enabled1 or r_enabled2

g_enabled1 = close > mid1
g_enabled2 = (range > rangeAvg) and (close > u1) and (volume > volumeA)
g_enabled3 = (high > high1) and (range < rangeAvg/1.5) and (volume < volumeA)
g_enabled4 = (low < low1) and (range < rangeAvg/1.5) and (volume > volumeA)
g_enabled = g_enabled1 or g_enabled2 or g_enabled3 or g_enabled4

gr_enabled1 = (range > rangeAvg) and (close > d1) and (close < u1) and (volume > volumeA) and (volume < volumeA*1.5) and (volume > volume[1])
gr_enabled2 = (range < rangeAvg/1.5) and (volume < volumeA/1.5)
gr_enabled3 = (close > d1) and (close < u1)
gr_enabled = gr_enabled1 or gr_enabled2 or gr_enabled3

barcolor(r_enabled ? red : g_enabled ? lime : gr_enabled ? gray : yellow)