//
// @author LazyBear 
// List of all my indicators: 
// https://docs.google.com/document/d/15AGCufJZ8CIUvwFJ9W-IKns88gkWOKBCvByMEvm5MLo/edit?usp=sharing
//
study("Short-term Volume And Price Oscillator [LazyBear]", shorttitle="SVAPO_LB")
length=input(8, title="SVAPO Period", minval=2, maxval=20)
cutoff=input(1, title="Minimum %o price change", maxval=10, minval=0)
devH=input(1.5, title="Stdev High", maxval=5, minval=0.1)
devL=input(1.3, title="Stdev Low", maxval=5, minval=0.1)
stdevper=input(100, title="Stdev Period", maxval=200, minval=1)

calc_tema(s, length) =>
 ema1 = ema(s, length)
 ema2 = ema(ema1, length)
 ema3 = ema(ema2, length)
 3 * (ema1 - ema2) + ema3

calc_linregslope(C, tp) =>
 ((tp*(sum(cum(1)*C,tp)))-(sum(cum(1),tp)*(sum(C,tp))))/((tp*sum(pow(cum(1),2),tp))-pow(sum(cum(1),tp),2))

calc_OR2(x) => 
 y=x
 (y == true) or (y[1] == true)

haOpen=(ohlc4[1] + nz(haOpen[1]))/2
haCl=(ohlc4+haOpen+max(high, haOpen)+min(low, haOpen))/4
haC=haCl
vola = calc_tema(haC,length)*100
vb = calc_tema(volume,length)
vave = sma(vb, length)
vmax = highest(vb, length*3)
vmin = lowest(vb, length*3)
vola2 = calc_tema(vb,length)
nr=(vola2-vave)/(vmax-vmin)*100

R1=calc_OR2(abs((haCl/haCl[1]-1)*100)>=cutoff)
svapo = iff(R1, nr, nz(svapo[1]))

plot(svapo, color=black, linewidth=2, title="SVAPO")

upbound=devH*stdev(svapo,stdevper)
lowbound=-devL*stdev(svapo,stdevper)

ul=plot(upbound, color=red), ll=plot(lowbound, color=green), zl=plot(0, color=gray)
fill(ul,ll, color=silver, transp=80)