//
// @author LazyBear 
// List of all my indicators: 
// https://docs.google.com/document/d/15AGCufJZ8CIUvwFJ9W-IKns88gkWOKBCvByMEvm5MLo/edit?usp=sharing
// 
study(title="Variable Moving Average Bands [LazyBear]", shorttitle="VMABANDS_LB", overlay=true)
src=close
l=input(6, title="VMA Length") 
bm=input(1.5, title="Bands Multipler")
std=input(false, title="Show Trend Direction")
bc=input(false, title="Color bars based on Trend")
calc_vma(src, l) => 
 k = 1.0/l
 pdm = max((src - src[1]), 0)
 mdm = max((src[1] - src), 0)
 pdmS = ((1 - k)*nz(pdmS[1]) + k*pdm)
 mdmS = ((1 - k)*nz(mdmS[1]) + k*mdm)
 s = pdmS + mdmS
 pdi = pdmS/s
 mdi = mdmS/s
 pdiS = ((1 - k)*nz(pdiS[1]) + k*pdi)
 mdiS = ((1 - k)*nz(mdiS[1]) + k*mdi)
 d = abs(pdiS - mdiS)
 s1 = pdiS + mdiS
 iS = ((1 - k)*nz(iS[1]) + k*d/s1)
 hhv = highest(iS, l) 
 llv = lowest(iS, l) 
 d1 = hhv - llv
 vI = (iS - llv)/d1
 vma=(1 - k*vI)*n