//
// @author LazyBear 
// List of all my indicators: 
// https://docs.google.com/document/d/15AGCufJZ8CIUvwFJ9W-IKns88gkWOKBCvByMEvm5MLo/edit?usp=sharing
// 
study("EMA Wave Indicator [LazyBear]", shorttitle="EWI_LB")
alength=input(5, title="Wave A Length"), blength=input(25, title="Wave B Length"), clength=input(50, title="Wave C Length")
lengthMA=input(4, title="Wave SMA Length")
mse=input(false, title="Identify Spikes/Exhaustions")
cutoff = input(10, title="Cutoff")
ebc=input(false, title="Color Bars on Spikes/Exhaustions")
src=hlc3
ma(s,l) => ema(s,l)
wa=sma(src-ma(src, alength),lengthMA) 
wb=sma(src-ma(src, blength),lengthMA) 
wc=sma(src-ma(src, clength),lengthMA) 
wcf=(wb != 0) ? (wc/wb > cutoff) : false
wbf=(wa != 0) ? (wb/wa > cutoff) : false
plot(0, color=gray, title="ZeroLine")
plot(wc, color=maroon, style=histogram, linewidth=3, title="WaveC")
plot(mse and wcf?wc:na, color=fuchsia, style=histogram, linewidth=3, title="WaveC Spike")
plot(wb, color=blue, style=histogram, linewidth=3, title="WaveB")
plot(mse and wbf?wb:na, color=fuchsia, style=histogram, linewidth=3, title="WaveB Spike")
plot(wa, color=red, style=histogram,