study("DecisionPoint Volume Swenlin Trading Oscillator [LazyBear]", shorttitle="DVSTO_LB", overlay=false, precision=5)
mkt = input (defval=1, minval=0, maxval=4, title="Market (0=>AMEX/NASD/NYSE Combined, 1=NYSE, 2=NASDAQ, 3=AMEX, 4=CUSTOM)")
aic=input(defval="AVVD", title="CUSTOM: Advancing Volume Symbol", type=symbol)
dic=input(defval="DVCD", title="CUSTOM: Declining Volume Symbol", type=symbol)
res = isintraday?"D":period // dont go below "D"
advn="AVVN", decn="DVCN" // NYSE
advnq="AVVQ", decnq="DVCQ" // NASDAQ
advna="AVVA", decna="DVCA" // AMEX
advc="(AVVN+AVVQ+AVVA)/3.0", decc="(DVCN+DVCQ+DVCA)/3.0"
adv= security(mkt==0? advc:mkt == 1? advn:mkt == 2? advnq:mkt == 3? advna:aic, res, close)
dec= security(mkt==0? decc:mkt == 1? decn:mkt == 2? decnq:mkt == 3? decna:dic, res, close)
i=(adv-dec)/(adv+dec)
sto=sma(ema(i * 1000, 4), 5)
sh=input(true, title="Show Histo")
plot(0, color=gray, title="MidLine")
plot(sh?sto:na, style=histogram, color=sto>0?sto>sto[1]?green:orange:sto<sto[1]?red:orange, title="Histo")
plot(sto, linewidth=2, color=maroon,